/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import DataBeans.ListaDataPendiente;
import Datatypes.DataPendiente;
import Datatypes.DataVersion;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import tprog.FabricaSistema;
import tprog.InterfazCategoriaJuego;

/**
 *
 * @author Usuario
 */
public class AceptarRechazarVersion extends javax.swing.JInternalFrame {
    public class MyTableModel extends DefaultTableModel {
           public MyTableModel() {
                super();
            }
            public boolean isCellEditable(int row, int col) {
                return false;
             }
     }

    private AceptarRechazarVersion.MyTableModel modeloV = new AceptarRechazarVersion.MyTableModel();
    private InterfazCategoriaJuego icj = FabricaSistema.getInstance().getInterfazCategoriaJuego();
    private boolean conf = false;
    /**
     * Creates new form AceptarRechazarVersion
     */
    public AceptarRechazarVersion() {
        initComponents();
        labelMotivo.setVisible(false);
        motivo.setVisible(false);
        tablaV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modeloV.addColumn("Juego");
        modeloV.addColumn("Version");
        modeloV.addColumn("Desarrollador");
        
        cargarTabla(modeloV);
    }

    private void cargarTabla(MyTableModel m){
        
        ListaDataPendiente l = icj.listarVersionPendientes();
        List<DataPendiente> lvp = l.getLista();
        Iterator it = lvp.iterator();
        while(it.hasNext()){
            DataPendiente dp = (DataPendiente) it.next();
            Object [] fila = new Object[3];
            fila[0] = dp.getNomJuego();
            fila[1] = dp.getNumVersion();
            fila[2] = dp.getNickDesarrollador();
            modeloV.addRow(fila);
        
        }
        tablaV.setModel(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoBoton = new javax.swing.ButtonGroup();
        jPanel1 =  new panel("/Imagenes/Fondo.jpg");
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tamanio = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JRadioButton();
        botonRechazar = new javax.swing.JRadioButton();
        labelMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo = new javax.swing.JTextArea();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Aceptar/Rechazar Version");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaV.setModel(this.modeloV);
        tablaV.setFocusable(false);
        tablaV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaV);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, 352, 355));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Versiones pendientes de aprobacion:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, -1, -1));

        jLabel2.setText("Tamaño version:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 103, -1, -1));

        tamanio.setEditable(false);
        jPanel1.add(tamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 101, 94, -1));

        tipoBoton.add(botonAceptar);
        botonAceptar.setSelected(true);
        botonAceptar.setText("Aceptar Version");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 172, -1, -1));
        botonAceptar.getAccessibleContext().setAccessibleName("");

        tipoBoton.add(botonRechazar);
        botonRechazar.setText("Rechazar Version");
        botonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRechazarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 172, -1, -1));
        botonRechazar.getAccessibleContext().setAccessibleName("");

        labelMotivo.setText("Motivo de rechazo:");
        jPanel1.add(labelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 244, -1, -1));

        motivo.setColumns(20);
        motivo.setRows(5);
        motivo.setBorder(null);
        jScrollPane1.setViewportView(motivo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 277, 303, -1));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        jPanel1.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVMouseClicked
        int F = tablaV.rowAtPoint(evt.getPoint());
        String nomJ = (String) tablaV.getValueAt(F, 0);
        String ver = (String)tablaV.getValueAt(F, 1);
        DataVersion dv = icj.seleccionarVersion(nomJ, ver);
        String tam = Double.toString(dv.getTamanio());
        tamanio.setText(tam);
        conf= true;
    }//GEN-LAST:event_tablaVMouseClicked

    private void botonRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRechazarActionPerformed
        labelMotivo.setVisible(true);
        motivo.setVisible(true);
        
    }//GEN-LAST:event_botonRechazarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        labelMotivo.setVisible(false);
        motivo.setVisible(false);
        motivo.setText("");
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

        if (conf == true){

            ButtonModel tipo     = tipoBoton.getSelection();
            String tipoOp = null;
            if (tipo == botonAceptar.getModel())
                tipoOp = "Aceptar";
            else
                tipoOp = "Rechazar";

            if(tipoOp.equals("Rechazar")){
                String mot = motivo.getText();
                if (mot == null)
                    JOptionPane.showMessageDialog(null,"Debe ingresar un motivo.", "ERROR", 2);
                else{

                    icj.rechazarVersion(mot);
                    JOptionPane.showMessageDialog(null,"Version rechazada con exito!");
                    MyTableModel mod = (MyTableModel) tablaV.getModel();
                    for (int i=mod.getRowCount()-1; i>-1;i--){
                            mod.removeRow(i);
                        }
                    cargarTabla(mod);
                    motivo.setText("");
                }
            }else{
                icj.aceptarVersion();
                JOptionPane.showMessageDialog(null,"Version aceptada con exito!");
              
                MyTableModel mod = (MyTableModel) tablaV.getModel();
                for (int i=mod.getRowCount()-1; i>-1;i--){
                        mod.removeRow(i);
                    }
                cargarTabla(mod);
            }
        }else{

            JOptionPane.showMessageDialog(null,"Debe seleccionar un juego.", "ERROR", 2);
        }

    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
          this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonAceptar;
    private javax.swing.JRadioButton botonRechazar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelMotivo;
    private javax.swing.JTextArea motivo;
    private javax.swing.JTable tablaV;
    private javax.swing.JTextField tamanio;
    private javax.swing.ButtonGroup tipoBoton;
    // End of variables declaration//GEN-END:variables
}
