/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaUsuario.java
 *
 * Created on 16-ago-2012, 12:46:43
 */

package Swing;

import Datatypes.DataArchivo;
import Datatypes.DataFecha;
import Datatypes.DataInfoJuego;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import tprog.FabricaSistema;
import tprog.InterfazUsuario;

/**
 *
 * @author alexander
 */
public class AltaUsuario extends javax.swing.JInternalFrame {
    
    private File fileImagen = null;
    private InterfazUsuario iu = FabricaSistema.getInstance().getInterfazUsuario();

    private byte[] fileToBytes(File file){
        byte[] data = null;
        try {
            FileInputStream theIn = new FileInputStream(file);
            data = new byte[(int)file.length()];
            theIn.read(data);
            theIn.close();
        } catch (FileNotFoundException ex2) {
            Logger.getLogger(DataInfoJuego.class.getName()).log(Level.SEVERE, null, ex2);
            data = null;
        } catch (IOException ex) {
            Logger.getLogger(DataInfoJuego.class.getName()).log(Level.SEVERE, null, ex);
            data = null;
        } finally {
            return data;
        }
    }
    /** Creates new form AltaUsuario */
    public AltaUsuario() {
        initComponents();
        TextoWeb.setVisible(false);
        web.setVisible(false);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDeUsuario = new javax.swing.ButtonGroup();
        Fondo = new panel("/Imagenes/Fondo.jpg");
        Imagen = new javax.swing.JLabel();
        BotonCargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CampoDeDatos = new javax.swing.JPanel();
        Nick = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        FNac = new javax.swing.JLabel();
        TextoNick = new javax.swing.JTextField();
        TextoApellido = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoEmail = new javax.swing.JTextField();
        TextoWeb = new javax.swing.JTextField();
        DatosEdad = new javax.swing.JSlider();
        Dia = new javax.swing.JComboBox();
        Mes = new javax.swing.JComboBox();
        Anio = new javax.swing.JComboBox();
        TipoUsuario = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        web = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        Nick1 = new javax.swing.JLabel();
        TextoContraseña = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Usuario");

        Imagen.setIcon(new ImageIcon("/Imagenes/default.jpg"));

        BotonCargar.setText("Cargar foto");
        BotonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CampoDeDatos.setBackground(new java.awt.Color(245, 241, 241));
        CampoDeDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos de usuario"));
        CampoDeDatos.setOpaque(false);

        Nick.setText("Nick:");

        Nombre.setText("Nombre:");

        Apellido.setText("Apellido:");

        Email.setText("Email:");

        Edad.setText("Edad:");

        FNac.setText("Fecha de nacimiento:");

        TextoNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNickActionPerformed(evt);
            }
        });

        TextoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApellidoActionPerformed(evt);
            }
        });

        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });

        TextoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEmailActionPerformed(evt);
            }
        });

        TextoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoWebActionPerformed(evt);
            }
        });

        DatosEdad.setFont(new java.awt.Font("Dialog", 1, 8));
        DatosEdad.setMajorTickSpacing(10);
        DatosEdad.setMaximum(162);
        DatosEdad.setMinorTickSpacing(1);
        DatosEdad.setValue(0);
        DatosEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DatosEdad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DatosEdadStateChanged(evt);
            }
        });

        Dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));

        Anio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900", "1899", "1898", "1897", "1896", "1895", "1894", "1893", "1892", "1891", "1890", "1889", "1888", "1887", "1886", "1885", "1884", "1883", "1882", "1881", "1880", "1879", "1878", "1877", "1876", "1875", "1874", "1873", "1872", "1871", "1870", "1869", "1868", "1867", "1866", "1865", "1864", "1863", "1862", "1861", "1860", "1859", "1858", "1857", "1856", "1855", "1854", "1853", "1852", "1851", "1850" }));

        TipoUsuario.setText("Tipo de usuario:");

        TipoDeUsuario.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cliente");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        TipoDeUsuario.add(jRadioButton2);
        jRadioButton2.setText("Desarrollador");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        web.setText("Sitio web");

        labelEdad.setText("0");

        Nick1.setText("Contraseña:");

        TextoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CampoDeDatosLayout = new javax.swing.GroupLayout(CampoDeDatos);
        CampoDeDatos.setLayout(CampoDeDatosLayout);
        CampoDeDatosLayout.setHorizontalGroup(
            CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoDeDatosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CampoDeDatosLayout.createSequentialGroup()
                        .addComponent(TipoUsuario)
                        .addGap(52, 52, 52)
                        .addComponent(jRadioButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jRadioButton2))
                    .addGroup(CampoDeDatosLayout.createSequentialGroup()
                        .addComponent(FNac)
                        .addGap(29, 29, 29)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CampoDeDatosLayout.createSequentialGroup()
                        .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nick1)
                            .addComponent(Nick)
                            .addComponent(Nombre)
                            .addComponent(Apellido)
                            .addComponent(Email)
                            .addComponent(web)
                            .addComponent(Edad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CampoDeDatosLayout.createSequentialGroup()
                                .addComponent(DatosEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextoWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNick, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        CampoDeDatosLayout.setVerticalGroup(
            CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoDeDatosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nick)
                    .addComponent(TextoNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nick1)
                    .addComponent(TextoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(TipoUsuario))
                .addGap(17, 17, 17)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(web)
                    .addComponent(TextoWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Edad)
                    .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatosEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CampoDeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FNac))
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(BotonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)))
                .addComponent(CampoDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonCargar)
                        .addGap(112, 112, 112)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CampoDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
        JFileChooser buscarImagen = new JFileChooser();
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("Imágenes (bmp, jpg, png)", new String[]{"bmp","jpg","png"});
        buscarImagen.setAcceptAllFileFilterUsed(false);
        buscarImagen.setFileFilter(filtro);

        int result = buscarImagen.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION){
            fileImagen = buscarImagen.getSelectedFile();
            ImageIcon imageIcon = new ImageIcon(fileImagen.getPath());
            Imagen.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(Imagen.getWidth(), -1, Image.SCALE_AREA_AVERAGING)));
            Imagen.repaint();

            //******************** GUARDAR IMGENES EN CARPETA ********************

            String name = fileImagen.getName();
            int pos = name.lastIndexOf('.');
            String ext = name.substring(pos+1);

            File directorio = new File("Imagenes/");
            directorio.mkdir();
            
            File destino = new File("Imagenes/"+TextoNick.getText()+"."+ext);
            try{
                InputStream in = new FileInputStream(fileImagen);
                OutputStream out = new FileOutputStream(destino);

                byte[] buffer = new byte[1024];
                int tamanoRes;


                    while ((tamanoRes = in.read(buffer)) > 0) {
                        out.write(buffer, 0, tamanoRes);
                    }
                    in.close();
                    out.close();
                
            }
            catch (IOException ex) {
                Logger.getLogger(AltaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_BotonCargarActionPerformed

    private void TextoNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNickActionPerformed

    private void TextoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoApellidoActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoWebActionPerformed

    private void TextoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEmailActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
          TextoWeb.setVisible(true);
          web.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
          web.setVisible(false);
          TextoWeb.setVisible(false);
          TextoWeb.setText("");

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         iu.cancelar();
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DatosEdadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DatosEdadStateChanged
        int i    = DatosEdad.getValue();
        String a = Integer.toString(i);
        labelEdad.setText(a);
    }//GEN-LAST:event_DatosEdadStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nick     = TextoNick.getText();
        String pass     = TextoContraseña.getText();
        String nombre   = TextoNombre.getText();
        String apellido = TextoApellido.getText();
        String email    = TextoEmail.getText();
        String url      = TextoWeb.getText();
        int edad        = DatosEdad.getValue();
        int mes         = Mes.getSelectedIndex() +1;
        int dia         = Dia.getSelectedIndex() +1;
        String anioS    = (String) Anio.getSelectedItem();
        int anio        = Integer.parseInt(anioS);


        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String hoy = formato.format(fechaActual);
        String[] dat2 = hoy.split("/");
        int anos1 = Integer.parseInt(dat2[2]) - anio;
        int mes1 = Integer.parseInt(dat2[1]) - mes;
        if (mes1 < 0) {
          anos1 = anos1 - 1;
        } else if (mes == 0) {
          int dia1 = Integer.parseInt(dat2[0]) - dia;
          if (dia1 > 0) {
            anos1 = anos1 - 1;
          }
        }
        if(anos1!=edad){
            JOptionPane.showMessageDialog(null,"La edad no se corresponde\n con la fecha de nacimiento", "ERROR", 2);
        }else{



            ButtonModel tipo     = TipoDeUsuario.getSelection();
            String tipoU = null;
            if (tipo == jRadioButton1.getModel())
                tipoU = "Cliente";
            else
                tipoU = "Desarrollador";

            if((nick.equals(""))||(nombre.equals(""))||
              (apellido.equals(""))||(email.equals(""))||((tipoU.equals("Desarrollador"))&&(url.equals("")))){
                  JOptionPane.showMessageDialog(null,"Hay campos incompletos.\nPor favor complete los datos faltantes.", "ERROR", 2);
            }
            else{
                
                boolean NoExiste = (iu.ingresarPerfil(nick, email));

                if (NoExiste){
                    DataFecha fecha = new DataFecha();
                    fecha.setDia(dia);
                    fecha.setMes(mes);
                    fecha.setAnio(anio);

                    DataArchivo dArchivo;
                    if (fileImagen !=null && fileImagen.length()!=0){
                         dArchivo = new DataArchivo();
                         dArchivo.setArchivo(fileToBytes(fileImagen));

                         int index = fileImagen.getName().lastIndexOf(".");
                         String extImg = fileImagen.getName().substring(index);
                         dArchivo.setExtencion(extImg);
                    }else
                         dArchivo = new DataArchivo();

                    if (tipoU.equals("Desarrollador")){
                         iu.altaDesarrollador(nombre, apellido, fecha, edad, dArchivo, url, pass);
                    }
                    else{
                        iu.altaCliente(nombre, apellido, fecha, edad, dArchivo, pass);
                    }
                    JOptionPane.showMessageDialog(null,"Usuario registrado con éxito!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "El nick o el email ingresado\n  ya existe en el sistema", "ERROR", 2);
                    TextoNick.setText("");
                    TextoEmail.setText("");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Anio;
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BotonCargar;
    private javax.swing.JPanel CampoDeDatos;
    private javax.swing.JSlider DatosEdad;
    private javax.swing.JComboBox Dia;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FNac;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Imagen;
    private javax.swing.JComboBox Mes;
    private javax.swing.JLabel Nick;
    private javax.swing.JLabel Nick1;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField TextoApellido;
    private javax.swing.JTextField TextoContraseña;
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JTextField TextoNick;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoWeb;
    private javax.swing.ButtonGroup TipoDeUsuario;
    private javax.swing.JLabel TipoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables

}
