/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompraJuego.java
 *
 * Created on Aug 24, 2012, 12:39:38 PM
 */

package Swing;

import DataBeans.ListaDataJuego;
import Datatypes.DataCompra;
import Datatypes.DataInfoJuego;
import Datatypes.DataJuego;
import Exceptions.ExcAccesoUsuario;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tprog.FabricaSistema;
import tprog.InterfazCategoriaJuego;

/**
 *
 * @author tprog125
 */
public class CompraJuego extends javax.swing.JInternalFrame {

    public class MyTableModel extends DefaultTableModel {
           public MyTableModel() {
                super();
            }
            public boolean isCellEditable(int row, int col) {
                return false;
             }
     }

    private MyTableModel modeloJ = new MyTableModel();
    private InterfazCategoriaJuego icj = FabricaSistema.getInstance().getInterfazCategoriaJuego();
    /** Creates new form CompraJuego */
    public CompraJuego() {
        initComponents();
        desc.setWrapStyleWord(true);
        tablaJuegos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modeloJ.addColumn("Nombre Juego");
        modeloJ.addColumn("Precio");
        TableColumn column = null;
        column = tablaJuegos.getColumnModel().getColumn(0);

        column.setPreferredWidth(180);
        column = tablaJuegos.getColumnModel().getColumn(1);
           
        column.setPreferredWidth(20); //sport column is bigger
         
       
        nickLabel.setEnabled(false);
        botonCompra.setEnabled(false);
        nickCliente.setEnabled(false);
        ListaDataJuego l = icj.listarJuegos();
        List<DataJuego> ldj = l.getLista();
        Iterator it = ldj.iterator();
        while (it.hasNext()){
            DataJuego data = (DataJuego) it.next();
            Object [] fila = new Object[2];
            fila[0] = data.getNombre();
            String precio = Double.toString(data.getPrecio());
            fila[1] = "U$S "+ precio;

            modeloJ.addRow (fila); // Añade una fila al final
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new panel("/Imagenes/Fondo.jpg");
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJuegos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        nickLabel = new javax.swing.JLabel();
        nickCliente = new javax.swing.JTextField();
        botonCompra = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Compra Juego");

        tablaJuegos.setModel(this.modeloJ);
        tablaJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJuegosMouseClicked(evt);
            }
        });
        tablaJuegos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaJuegosMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tablaJuegos);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24));
        jLabel1.setText("Juegos");

        desc.setColumns(20);
        desc.setLineWrap(true);
        desc.setRows(5);
        jScrollPane2.setViewportView(desc);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("Descripción:");

        nickLabel.setText("Nick Cliente:");

        nickCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nickClienteKeyPressed(evt);
            }
        });

        botonCompra.setText("Comprar");
        botonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(nickLabel)
                                        .addGap(133, 133, 133))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(nickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(nickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(nickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaJuegosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuegosMouseMoved
        int F = tablaJuegos.rowAtPoint(evt.getPoint());
        String nomJuego = (String)tablaJuegos.getValueAt(F, 0);
        DataInfoJuego data = icj.seleccionarJuego(nomJuego);
        desc.setText(data.getDescripcion());
    }//GEN-LAST:event_tablaJuegosMouseMoved

    private void tablaJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJuegosMouseClicked
        int F = tablaJuegos.rowAtPoint(evt.getPoint());
        String nomJuego = (String)tablaJuegos.getValueAt(F, 0);
        icj.ingresarNombreJuego(nomJuego);
        MouseMotionListener[] m = tablaJuegos.getMouseMotionListeners();
        if (m.length>1){
            tablaJuegos.removeMouseMotionListener(m[1]);
        }
        DataInfoJuego data = icj.seleccionarJuego(nomJuego);
        desc.setText(data.getDescripcion());
        nickLabel.setEnabled(true);
        botonCompra.setEnabled(true);
        nickCliente.setEnabled(true);
    }//GEN-LAST:event_tablaJuegosMouseClicked

    private void botonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompraActionPerformed
        confirmar();
    }//GEN-LAST:event_botonCompraActionPerformed

    private void nickClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nickClienteKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           confirmar();
       }
    }//GEN-LAST:event_nickClienteKeyPressed

    private void confirmar(){
        String nick = nickCliente.getText();
        if(icj.perteneceUsuario(nick)){
            DateFormat dateFormat = new SimpleDateFormat("dd/MM HH:mm");
            Date date = new Date();
            String fecha = dateFormat.format(date);
            try{
                DataCompra dc = icj.ingresarDatosCliente(nick, fecha);
                int confirmado = JOptionPane.showConfirmDialog(null, "¿Confirmar compra del cliente " + nick + " en la fecha " + fecha + "?", "CONFIRMAR COMPRA", 2);

                if (JOptionPane.OK_OPTION == confirmado){
                    icj.registrarCompra();
                    JOptionPane.showMessageDialog(null, "¡Compra realizada con éxito!");
                    this.dispose();
                }else{
                    icj.terminar();
                    this.dispose();
                }
            }
            catch(ExcAccesoUsuario e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                nickCliente.setText("");
            }


        }else{
            JOptionPane.showMessageDialog(null, "El cliente ingresado no es correcto");
            nickCliente.setText("");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCompra;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nickCliente;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JTable tablaJuegos;
    // End of variables declaration//GEN-END:variables

}
