/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaJuego.java
 *
 * Created on 19-ago-2012, 16:51:15
 */

package Swing;

import DataBeans.DataTreeMap;
import DataBeans.ListaDataJuego;
import Datatypes.DataJuego;
import Datatypes.DataInfoJuego;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JDesktopPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import tprog.Categoria;
import tprog.FabricaSistema;
import tprog.InterfazCategoriaJuego;

/**
 *
 * @author alexander
 */
public class ConsultaJuego extends javax.swing.JInternalFrame {

    public class MyTableModel extends DefaultTableModel {
           public MyTableModel() {
                super();
            }
            public boolean isCellEditable(int row, int col) {
                return false;
             }
     }

    private InterfazCategoriaJuego icj = FabricaSistema.getInstance().getInterfazCategoriaJuego();
    private MyTableModel modeloC = new MyTableModel();
    private MyTableModel modeloJ = new MyTableModel();

    /** Creates new form ConsultaJuego */
    public ConsultaJuego() {
        initComponents();
        jLabel2.setVisible(false);
        TablaJuegos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaCat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DataTreeMap d = icj.getListaCategoria();
        TreeMap<String, Categoria> coleccionCat = d.getLista();

        modeloC.addColumn("Categorías");
        modeloJ.addColumn("Juegos Por categorías");

         Set<String> listaKey = coleccionCat.keySet();

         Iterator it = listaKey.iterator();

         while (it.hasNext()){
            String s = (String) it.next();
            Object [] fila = new Object[1];
            fila[0] = s;

            modeloC.addRow (fila); // Añade una fila al final
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new panel("/Imagenes/Fondo.jpg");
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaCat = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaJuegos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Juego");

        TablaCat.setModel(this.modeloC);
        TablaCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaCat);

        TablaJuegos.setModel(this.modeloJ);
        TablaJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaJuegosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaJuegos);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("Seleccione una categoría");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setText("Seleccione un juego");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCatMouseClicked
       
       modeloJ.setRowCount(0);

        int F = TablaCat.rowAtPoint(evt.getPoint());
        String Cat = (String)TablaCat.getValueAt(F, 0);
        ListaDataJuego l = icj.listarJuegosAprobadosPorCat(Cat);
        List<DataJuego> lista = l.getLista();


        Iterator it = lista.iterator();

         while (it.hasNext()){
            DataJuego dj = (DataJuego) it.next();
            Object [] fila = new Object[1];
            fila[0] = dj.getNombre();
            modeloJ.addRow (fila); // Añade una fila al final
        }
        jLabel2.setVisible(true);
}//GEN-LAST:event_TablaCatMouseClicked

    private void TablaJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaJuegosMouseClicked

        int F = TablaJuegos.rowAtPoint(evt.getPoint());
        String nomJuego = (String)TablaJuegos.getValueAt(F, 0);
        DataInfoJuego data = icj.seleccionarJuego(nomJuego);
        JDesktopPane Esc = this.getDesktopPane();
        DescripcionJuego dj = new DescripcionJuego(data);
        Esc.add(dj);
        dj.show();
    }//GEN-LAST:event_TablaJuegosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCat;
    private javax.swing.JTable TablaJuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

}
