/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DescripcionJuego.java
 *
 * Created on Aug 23, 2012, 5:04:27 PM
 */

package Swing;
import Datatypes.DataInfoJuego;
import Datatypes.DataNodoComentario;
import Datatypes.DataVersion;
import java.util.Iterator;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import tprog.FabricaSistema;
import tprog.InterfazCategoriaJuego;
/**
 *
 * @author tprog129
 */
public class DescripcionJuego extends javax.swing.JInternalFrame {

      public class MyTableModel extends DefaultTableModel {
           public MyTableModel() {
                super();
            }
            public boolean isCellEditable(int row, int col) {
                return false;
             }
     }

    private InterfazCategoriaJuego icj = FabricaSistema.getInstance().getInterfazCategoriaJuego();
    private MyTableModel modeloC = new MyTableModel();
    private MyTableModel modeloCom = new MyTableModel();
    private MyTableModel modeloV = new MyTableModel();

   public DescripcionJuego(DataInfoJuego j) {
        initComponents();

        List<String> coleccionCat = j.getListaCategorias();
        List<String> coleccionCom = j.getListaCompradores();
        List<DataVersion> coleccionVA = j.getListaVersionAprobadas();
        jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modeloC.addColumn("Categorías");
        modeloCom.addColumn("Compradores");
        modeloV.addColumn("Número");
        modeloV.addColumn("Tamaño");
        
        Iterator itV = coleccionVA.iterator();
        while(itV.hasNext()){
            DataVersion dv = (DataVersion) itV.next();
            Object [] fila2 = new Object[2];
            fila2[0] = dv.getNumV();
            String tamanio = Double.toString(dv.getTamanio());
            fila2[1] = tamanio;
            
            modeloV.addRow (fila2);
        }
        
        
        Iterator itC = coleccionCom.iterator();
        while (itC.hasNext()){
            String s1 = (String) itC.next();
            Object [] fila1 = new Object[1];
            fila1[0] = s1;
            modeloCom.addRow (fila1); // Añade una fila al final
        }

        Iterator it = coleccionCat.iterator();
        while (it.hasNext()){
            String s = (String) it.next();
            Object [] fila = new Object[1];
            fila[0] = s;
            modeloC.addRow (fila); // Añade una fila al final
        }      

        nombreJuego.setText(j.getNombre());
        Desarrollador.setText("Por "+j.getNickDesarrollador());
        Precio.setText("Precio: U$S "+Double.toString(j.getPrecio()));
        Tamano.setText("Tamaño: "+Double.toString(j.getTamanio())+ " KB");
        Desc.setText(j.getDescripcion());

        /****************** INICIALIZACION ARBOL COMENTARIOS *******************/

        DefaultTreeModel modelo = (DefaultTreeModel)arbol.getModel();
        DefaultMutableTreeNode cabeza = new DefaultMutableTreeNode ("Comentarios");
        modelo.setRoot(cabeza);
        arbol.setModel(modelo);

        /******************** AGREGACION DE LOS COMENTARIOS ********************/
        List<DataNodoComentario> comments = j.getComentarios();
        if (comments.isEmpty()){
            DefaultMutableTreeNode n1 = new DefaultMutableTreeNode ("El juego no posee comentarios");
            cabeza.add(n1);
        }
        else
            AgregarComentarios(cabeza, comments);


    }

   private void AgregarComentarios(DefaultMutableTreeNode nodo, List<DataNodoComentario> comments){

        Iterator it = comments.iterator();

        while(it.hasNext()){
            DataNodoComentario c = (DataNodoComentario) it.next();
            String f = c.getContenido().getFecha();
            String n = c.getContenido().getNick();
            String t = c.getContenido().getTexto();
            String Com = "<html>["+ f + " - Por " + n + "] <br><b>" + t +"<b></html>";

            DefaultMutableTreeNode n1 = new DefaultMutableTreeNode (Com);
            nodo.add(n1);
            
            List<DataNodoComentario> resp = c.getRespuestas();
            AgregarComentarios(n1,resp);
        }
        
         

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new panel("/Imagenes/Fondo.jpg");
        nombreJuego = new javax.swing.JLabel();
        Desarrollador = new javax.swing.JLabel();
        Tamano = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Precio1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Precio2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Descripción del Juego");

        nombreJuego.setFont(new java.awt.Font("Bitstream Charter", 1, 28));
        nombreJuego.setText("Nombre Juego");

        Desarrollador.setText("Desarrollador");

        Tamano.setText("Tamaño:");

        Precio.setText("Precio:");

        Precio1.setText("Descripción:");

        Desc.setEditable(false);
        jScrollPane2.setViewportView(Desc);

        jTable1.setModel(this.modeloCom);
        jTable1.setFocusable(false);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(this.modeloC);
        jTable2.setFocusable(false);
        jTable2.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        arbol.setAutoscrolls(true);
        arbol.setRowHeight(38);
        jScrollPane4.setViewportView(arbol);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable3.setModel(this.modeloV);
        jTable3.setFocusable(false);
        jTable3.setRowSelectionAllowed(false);
        jScrollPane5.setViewportView(jTable3);

        Precio2.setText("Versiones:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Desarrollador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(Precio1))
                    .addComponent(nombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tamano)
                            .addComponent(Precio)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Precio2))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Desarrollador)
                            .addComponent(Precio1))))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Tamano)
                        .addGap(18, 18, 18)
                        .addComponent(Precio)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Precio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desarrollador;
    private javax.swing.JTextPane Desc;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio1;
    private javax.swing.JLabel Precio2;
    private javax.swing.JLabel Tamano;
    private javax.swing.JTree arbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel nombreJuego;
    // End of variables declaration//GEN-END:variables

}
