/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarPerfil.java
 *
 * Created on 17-ago-2012, 15:23:41
 */

package Swing;

import Datatypes.DataArchivo;
import Datatypes.DataDesarrollador;
import Datatypes.DataFecha;
import Datatypes.DataInfoJuego;
import Datatypes.DataPerfil;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import tprog.Desarrollador;
import tprog.FabricaSistema;
import tprog.InterfazUsuario;
import tprog.Usuario;

/**
 *
 * @author alexander
 */
public class ModificarPerfil extends javax.swing.JInternalFrame {

    private File fileImagen = null;
    private InterfazUsuario iu = FabricaSistema.getInstance().getInterfazUsuario();

    private byte[] fileToBytes(File file){
        byte[] data = null;
        try {
            FileInputStream theIn = new FileInputStream(file);
            data = new byte[(int)file.length()];
            theIn.read(data);
            theIn.close();
        } catch (FileNotFoundException ex2) {
            Logger.getLogger(DataInfoJuego.class.getName()).log(Level.SEVERE, null, ex2);
            data = null;
        } catch (IOException ex) {
            Logger.getLogger(DataInfoJuego.class.getName()).log(Level.SEVERE, null, ex);
            data = null;
        } finally {
            return data;
        }
    }

    /** Creates new form ModificarPerfil */
    public ModificarPerfil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new panel("/Imagenes/Fondo.jpg");
        CampoDeDatos = new javax.swing.JPanel();
        Nick = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        FNac = new javax.swing.JLabel();
        TextoNick = new javax.swing.JTextField();
        TextoApellido = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoEmail = new javax.swing.JTextField();
        TextoWeb = new javax.swing.JTextField();
        Dia = new javax.swing.JComboBox();
        Mes = new javax.swing.JComboBox();
        Anio = new javax.swing.JComboBox();
        web = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        DatosEdad = new javax.swing.JSlider();
        RutaImagen = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        labelEdad = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        Confirmar1 = new javax.swing.JButton();
        Comentario = new javax.swing.JLabel();
        aModificar = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ImagenNueva = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar datos de usuario");

        CampoDeDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Modificar Datos"));
        CampoDeDatos.setOpaque(false);
        CampoDeDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nick.setText("Nick:");
        Nick.setEnabled(false);
        CampoDeDatos.add(Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        Nombre.setText("Nombre:");
        Nombre.setEnabled(false);
        CampoDeDatos.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 73, -1, -1));

        Apellido.setText("Apellido:");
        Apellido.setEnabled(false);
        CampoDeDatos.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 117, -1, -1));

        Email.setText("Email:");
        Email.setEnabled(false);
        CampoDeDatos.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 165, -1, -1));

        Edad.setText("Edad:");
        Edad.setEnabled(false);
        CampoDeDatos.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        FNac.setText("Fecha de nacimiento:");
        FNac.setEnabled(false);
        CampoDeDatos.add(FNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 328, -1, -1));

        TextoNick.setEnabled(false);
        TextoNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNickActionPerformed(evt);
            }
        });
        CampoDeDatos.add(TextoNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 30, 295, -1));

        TextoApellido.setEnabled(false);
        TextoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApellidoActionPerformed(evt);
            }
        });
        CampoDeDatos.add(TextoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 112, 295, -1));

        TextoNombre.setEnabled(false);
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });
        CampoDeDatos.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 68, 295, -1));

        TextoEmail.setEnabled(false);
        TextoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEmailActionPerformed(evt);
            }
        });
        CampoDeDatos.add(TextoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 160, 295, -1));

        TextoWeb.setEditable(false);
        TextoWeb.setEnabled(false);
        TextoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoWebActionPerformed(evt);
            }
        });
        CampoDeDatos.add(TextoWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 204, 295, -1));

        Dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Dia.setEnabled(false);
        CampoDeDatos.add(Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 323, -1, -1));

        Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        Mes.setEnabled(false);
        CampoDeDatos.add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 323, -1, -1));

        Anio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "2099", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970" }));
        Anio.setEnabled(false);
        CampoDeDatos.add(Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 323, -1, -1));

        web.setText("Sitio web");
        web.setEnabled(false);
        CampoDeDatos.add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 209, -1, -1));

        Imagen.setText("Imagen:");
        Imagen.setEnabled(false);
        CampoDeDatos.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 373, -1, -1));

        DatosEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DatosEdad.setEnabled(false);
        DatosEdad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DatosEdadStateChanged(evt);
            }
        });
        CampoDeDatos.add(DatosEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 270, 260, -1));

        RutaImagen.setEditable(false);
        RutaImagen.setEnabled(false);
        RutaImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaImagenActionPerformed(evt);
            }
        });
        CampoDeDatos.add(RutaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 368, 204, -1));

        BotonBuscar.setText("Buscar");
        BotonBuscar.setEnabled(false);
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        CampoDeDatos.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        labelEdad.setText("50");
        labelEdad.setEnabled(false);
        CampoDeDatos.add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 266, -1, -1));

        Confirmar.setText("Aceptar");
        Confirmar.setEnabled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        CampoDeDatos.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 80, -1));

        Confirmar1.setText("Cancelar");
        Confirmar1.setEnabled(false);
        Confirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmar1ActionPerformed(evt);
            }
        });
        CampoDeDatos.add(Confirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 90, -1));

        Comentario.setText("<html>Ingrese el nick del <br />usuario a modificar: </html>");

        aModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aModificarActionPerformed(evt);
            }
        });
        aModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aModificarKeyPressed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Foto de perfil");

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Modificar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(CampoDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(aModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Modificar)
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CampoDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNickActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoNickActionPerformed

    private void TextoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApellidoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoApellidoActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEmailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoEmailActionPerformed

    private void TextoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoWebActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoWebActionPerformed

    private void aModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aModificarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
       habilitarEdicion();
    }//GEN-LAST:event_ModificarActionPerformed

    private void RutaImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaImagenActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
       String nick     = TextoNick.getText();
       String nombre   = TextoNombre.getText();
       String apellido = TextoApellido.getText();
       String email    = TextoEmail.getText();
       String url      = TextoWeb.getText();
       int edad        = DatosEdad.getValue();
       int mes         = Mes.getSelectedIndex() +1;
       int dia         = Dia.getSelectedIndex() +1;
       String anioS    = (String) Anio.getSelectedItem();
       int anio        = Integer.parseInt(anioS);

       DataFecha df = new DataFecha();
       df.setDia(dia);
       df.setMes(mes);
       df.setAnio(anio);

        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String hoy = formato.format(fechaActual);
        String[] dat2 = hoy.split("/");
        int anos1 = Integer.parseInt(dat2[2]) - anio;
        int mes1 = Integer.parseInt(dat2[1]) - mes;
        if (mes1 < 0) {
          anos1 = anos1 - 1;
        } else if (mes == 0) {
          int dia1 = Integer.parseInt(dat2[0]) - dia;
          if (dia1 > 0) {
            anos1 = anos1 - 1;
          }
        }
        if(anos1!=edad){
            JOptionPane.showMessageDialog(null,"La edad no se corresponde\n con la fecha de nacimiento", "ERROR", 2);
        }else{

           boolean ok= true;
           Usuario u = iu.encontrarUsuario();
           String tipoU = "";

           if (u instanceof Desarrollador){
            tipoU = "Desarrollador";
           }

           if((nick.equals(""))||(nombre.equals(""))||
              (apellido.equals(""))||(email.equals(""))||((tipoU.equals("Desarrollador"))&&(url.equals("")))){
                  JOptionPane.showMessageDialog(null,"Hay campos incompletos.\nPor favor complete los datos faltantes.", "ERROR", 2);
            }
            else{
                  if (!nick.equals(u.getNick())){
                    ok = iu.modificarNick(nick);
                    if (!ok){
                        JOptionPane.showMessageDialog(null, "    El Nick ingresado\nya existe en el sistema", "ERROR", 2);
                        TextoNick.setText("");
                    }
                  }
                  if ((ok)&&(!email.equals(u.getMail()))){
                    ok = iu.modificarMail(email);
                    if (!ok){
                        JOptionPane.showMessageDialog(null, "    El email ingresado\nya existe en el sistema", "ERROR", 2);
                        TextoEmail.setText("");
                    }
                  }
                  if (ok){
                    iu.modificarApellido(apellido);
                    iu.modificarEdad(edad);
                    iu.modificarNombre(nombre);
                    iu.modificarFechaNac(df);
                    if(tipoU.equals("Desarrollador")) {
                          iu.modificarWeb(url);
                    }
                    if (fileImagen != null) {
                          DataArchivo dArchivo = new DataArchivo();
                          dArchivo.setArchivo(fileToBytes(fileImagen));

                          int index = fileImagen.getName().lastIndexOf(".");
                          String extImg = fileImagen.getName().substring(index);
                          dArchivo.setExtencion(extImg);

                          iu.modificarImagen(dArchivo);
                    }
                    JOptionPane.showMessageDialog(null, "Los datos fueron modificados\n              con éxito");
                    this.dispose();
                  }
            }
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void DatosEdadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DatosEdadStateChanged
        int i    = DatosEdad.getValue();
        String a = Integer.toString(i);
        labelEdad.setText(a);
    }//GEN-LAST:event_DatosEdadStateChanged

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        JFileChooser buscarImagen = new JFileChooser();
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("Imágenes (bmp, jpg, png)", new String[]{"bmp","jpg","png"});
        buscarImagen.setAcceptAllFileFilterUsed(false);
        buscarImagen.setFileFilter(filtro);


        int result = buscarImagen.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION){
            fileImagen = buscarImagen.getSelectedFile();
            ImageIcon imageIcon = new ImageIcon(fileImagen.getPath());
            RutaImagen.setText(fileImagen.getPath());
            ImagenNueva.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(ImagenNueva.getWidth(), -1, Image.SCALE_AREA_AVERAGING)));
            ImagenNueva.repaint();
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void Confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmar1ActionPerformed
        iu.terminar();
        this.dispose();
    }//GEN-LAST:event_Confirmar1ActionPerformed

    private void aModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aModificarKeyPressed
            if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                habilitarEdicion();
    }//GEN-LAST:event_aModificarKeyPressed

    private void habilitarEdicion(){
         if ((aModificar.getText()).equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese un Usuario.", "ERROR" , 2);
        }
        else{

            if (iu.perteneceUsuario(aModificar.getText())){

                DataPerfil Info = iu.verPerfil(aModificar.getText());
                int diaF  = Info.getFecha().getDia() -1;
                int mesF  = Info.getFecha().getMes() -1;
                int anioF = 2012 - Info.getFecha().getAnio() -1;

                Nick.setEnabled(true);        TextoNick.setEnabled(true);
                Nombre.setEnabled(true);      TextoNombre.setEnabled(true);
                Apellido.setEnabled(true);    TextoApellido.setEnabled(true);
                Email.setEnabled(true);       TextoEmail.setEnabled(true);
                Edad.setEnabled(true);        DatosEdad.setEnabled(true);
                labelEdad.setEnabled(true);

                if (Info instanceof DataDesarrollador){
                    DataDesarrollador dd= (DataDesarrollador) Info;
                    web.setEnabled(true);         TextoWeb.setEnabled(true);
                    TextoWeb.setText(dd.getWeb());
                    web.setVisible(true);         TextoWeb.setVisible(true);
                }
                else{
                    web.setVisible(false);         TextoWeb.setVisible(false);
                }

                FNac.setEnabled(true);        Dia.setEnabled(true);
                Mes.setEnabled(true);         Anio.setEnabled(true);
                Imagen.setEnabled(true);      BotonBuscar.setEnabled(true);
                RutaImagen.setEnabled(true);  Confirmar.setEnabled(true);
                Confirmar1.setEnabled(true);

                TextoNick.setText(Info.getNick());
                TextoNombre.setText(Info.getNombre());
                TextoApellido.setText(Info.getApellido());
                TextoEmail.setText(Info.getMail());
                DatosEdad.setValue(Info.getEdad());
                Dia.setSelectedIndex(diaF);
                Anio.setSelectedIndex(anioF);
                Mes.setSelectedIndex(mesF);

                ImageIcon imageIcon = new ImageIcon(Info.getImagenData());
                int i = imageIcon.getIconHeight();
                int j = imageIcon.getIconWidth();
                ImagenNueva.setHorizontalAlignment(SwingConstants.CENTER);
                if (i>j){
                    ImageIcon nuevoIcon = new ImageIcon(imageIcon.getImage().getScaledInstance(-1, ImagenNueva.getHeight(), Image.SCALE_AREA_AVERAGING));
                    ImagenNueva.setIcon(nuevoIcon);
                }
                else {
                    ImageIcon nuevoIcon = new ImageIcon(imageIcon.getImage().getScaledInstance(ImagenNueva.getWidth()*2/3, -1, Image.SCALE_AREA_AVERAGING));
                    ImagenNueva.setIcon(nuevoIcon);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "   El usuario ingresado\nno pertenece al sistema", "ERROR", 2);
                aModificar.setText("");
            }



        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Anio;
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JPanel CampoDeDatos;
    private javax.swing.JLabel Comentario;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Confirmar1;
    private javax.swing.JSlider DatosEdad;
    private javax.swing.JComboBox Dia;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FNac;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel ImagenNueva;
    private javax.swing.JComboBox Mes;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nick;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField RutaImagen;
    private javax.swing.JTextField TextoApellido;
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JTextField TextoNick;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoWeb;
    private javax.swing.JTextField aModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables

}
