
package tprog;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ControladorMovilService", targetNamespace = "http://tprog/", wsdlLocation = "http://pcunix46:9998/ws/ServiceMovil?wsdl")
public class ControladorMovilService
    extends Service
{

    private final static URL CONTROLADORMOVILSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(tprog.ControladorMovilService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = tprog.ControladorMovilService.class.getResource(".");
            url = new URL(baseUrl, "http://pcunix46:9998/ws/ServiceMovil?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://pcunix46:9998/ws/ServiceMovil?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTROLADORMOVILSERVICE_WSDL_LOCATION = url;
    }

    public ControladorMovilService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorMovilService() {
        super(CONTROLADORMOVILSERVICE_WSDL_LOCATION, new QName("http://tprog/", "ControladorMovilService"));
    }

    /**
     * 
     * @return
     *     returns InterfazMovil
     */
    @WebEndpoint(name = "ControladorMovilPort")
    public InterfazMovil getControladorMovilPort() {
        return super.getPort(new QName("http://tprog/", "ControladorMovilPort"), InterfazMovil.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfazMovil
     */
    @WebEndpoint(name = "ControladorMovilPort")
    public InterfazMovil getControladorMovilPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tprog/", "ControladorMovilPort"), InterfazMovil.class, features);
    }

}
