/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Movil.java
 *
 * Created on 02-nov-2012, 13:51:35
 */

package dispositivomovil;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import logica.ControladorDispositivo;
import logica.HiloConexion;

/**
 *
 * @author alexander
 */
public class Movil extends javax.swing.JFrame {

    /** Creates new form Movil */
    public Movil() {
        initComponents();
        Reloj obj = new Reloj(hora, nick);
        obj.start();
        HiloConexion con = new HiloConexion(conexion, desconexion, loading);
        con.start();
        simon s = new simon();
        escritorio.add(s);
        s.setVisible(true);
        s.setLocation(39, 126);
        desconexion.setVisible(false);
        loading.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new panel("/imagenes/movil.jpg");
        hora = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        conexion = new javax.swing.JLabel();
        desconexion = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Movil.class);
        escritorio.setBackground(resourceMap.getColor("escritorio.background")); // NOI18N
        escritorio.setName("escritorio"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(398, 706));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(resourceMap.getFont("hora.font")); // NOI18N
        hora.setForeground(resourceMap.getColor("hora.foreground")); // NOI18N
        hora.setName("hora"); // NOI18N
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 100, 80, 27));

        nick.setFont(resourceMap.getFont("nick.font")); // NOI18N
        nick.setForeground(resourceMap.getColor("nick.foreground")); // NOI18N
        nick.setText(resourceMap.getString("nick.text")); // NOI18N
        nick.setName("nick"); // NOI18N
        jPanel1.add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 100, 155, 30));

        jButton1.setIcon(resourceMap.getIcon("back.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("back.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setName("back"); // NOI18N
        jButton1.setPressedIcon(resourceMap.getIcon("back.pressedIcon")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 630, 34, 24));

        conexion.setIcon(resourceMap.getIcon("conexion.icon")); // NOI18N
        conexion.setText(resourceMap.getString("conexion.text")); // NOI18N
        conexion.setName("conexion"); // NOI18N
        jPanel1.add(conexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 36, 27));

        desconexion.setIcon(resourceMap.getIcon("desconexion.icon")); // NOI18N
        desconexion.setName("desconexion"); // NOI18N
        jPanel1.add(desconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 36, 27));

        loading.setIcon(resourceMap.getIcon("loading.icon")); // NOI18N
        loading.setText(resourceMap.getString("loading.text")); // NOI18N
        loading.setName("loading"); // NOI18N
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 30));

        jPanel1.setBounds(0, 0, 398, 706);
        escritorio.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JInternalFrame in = escritorio.getSelectedFrame();

        if (in != null){
            if (in.getName().equals("Login")||in.getName().equals("Jugar")||in.getName().equals("Com")
                || in.getName().equals("Rank")){
                 ControladorDispositivo c = ControladorDispositivo.getInstance();
                 simon s = null;

                 if (c.obtenerNickLogueado() == null){
                    s = new simon();
                 }else{
                    s = new simon(true);
                 }
                escritorio.add(s);
                s.setVisible(true);
                s.setLocation(39, 126);
                in.dispose();
            }            
            else if (in.getName().equals("LoginCom")||in.getName().equals("Comentar")){
                MostrarComentarios vistaComentarios = new MostrarComentarios();

                escritorio.add(vistaComentarios);
                vistaComentarios.ocultarBarraTitulo();
                vistaComentarios.show();
                vistaComentarios.setLocation(39, 126);
                in.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conexion;
    private javax.swing.JLabel desconexion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel nick;
    // End of variables declaration//GEN-END:variables

}
