/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panel.java
 *
 * Created on 26-ago-2009, 14:07:12
 */

package dispositivomovil;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author NeFaStO
 */
public class panel extends javax.swing.JPanel {
    ImageIcon imagen;
    /** Creates new form panel */
    public panel(String img) {
        initComponents();
        imagen = new ImageIcon(getClass().getResource(img));
        
        setSize(imagen.getIconWidth(),imagen.getIconHeight());
    }

    @Override
    protected void paintComponent(Graphics g) {
        Dimension d=getSize();
        g.drawImage(imagen.getImage(), 0, 0, d.width, d.height,this);
        setOpaque(false);
        super.paintComponent(g);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
