
package tprog;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ExcAltaJuego", targetNamespace = "http://tprog/")
public class ExcAltaJuego_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExcAltaJuego faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ExcAltaJuego_Exception(String message, ExcAltaJuego faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ExcAltaJuego_Exception(String message, ExcAltaJuego faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tprog.ExcAltaJuego
     */
    public ExcAltaJuego getFaultInfo() {
        return faultInfo;
    }

}
