
package tprog;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ExcAccesoUsuario", targetNamespace = "http://tprog/")
public class ExcAccesoUsuario_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExcAccesoUsuario faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ExcAccesoUsuario_Exception(String message, ExcAccesoUsuario faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ExcAccesoUsuario_Exception(String message, ExcAccesoUsuario faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tprog.ExcAccesoUsuario
     */
    public ExcAccesoUsuario getFaultInfo() {
        return faultInfo;
    }

}
