
package tprog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InterfazWeb", targetNamespace = "http://tprog/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterfazWeb {


    /**
     * 
     * @return
     *     returns tprog.DataTreeMap
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataTreeMap getListaCategoria();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void setNombreJuego(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns tprog.ListaNombreCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaNombreCategoria listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataJuego listarJuegosPorCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.DataInfoJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataInfoJuego seleccionarJuego(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     */
    @WebMethod
    public void altaJuego(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DataArchivo arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DataArchivo arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DataArchivo arg4,
        @WebParam(name = "arg5", partName = "arg5")
        double arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void seleccionarCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns tprog.ListaNickDesarrollador
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaNickDesarrollador listarDesarrolladores();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void seleccionarDesarrollador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @throws ExcAltaJuego_Exception
     */
    @WebMethod
    public void confirmar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExcAltaJuego_Exception
    ;

    /**
     * 
     * @return
     *     returns tprog.ListaDataJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataJuego listarJuegos();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns tprog.DataCompra
     * @throws ExcAccesoUsuario_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataCompra ingresarDatosCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws ExcAccesoUsuario_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void registrarCompra(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void terminar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void altaCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns tprog.ListaDataComentario
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataComentario obtenerComentarios(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean ingresarDatos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void agregarComentario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns tprog.ListaDataPendiente
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataPendiente listarVersionPendientes();

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaNombreJuegoConVersionesAprobadas
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaNombreJuegoConVersionesAprobadas listarJuegosConVersionesAprobadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void altaVersion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DataArchivo arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataJuego listarJuegosAprobadosPorCat(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataJuego listarJuegosCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataRechazada
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataRechazada listarVersionRechazadasPorDesarrollador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataPendiente
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataPendiente listarVersionPendientesPorDesarrollador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns tprog.ListaDataJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataJuego listarJuegosAprobadosSistema();

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.DataInfoJuego
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataInfoJuego seleccionarJuegoPorID(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void ingresarNombreJuegoPorID(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CantidadComprasJuegoMes")
    @WebResult(partName = "return")
    public int cantidadComprasJuegoMes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "AgregarReclamo")
    public void agregarReclamo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        EnumCategoriaReclamo arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaDataReclamo
     */
    @WebMethod(operationName = "ListarReclamos")
    @WebResult(partName = "return")
    public ListaDataReclamo listarReclamos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean ingresarPerfil(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean cancelar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     */
    @WebMethod
    public void altaDesarrollador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DataFecha arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DataArchivo arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     */
    @WebMethod
    public void altaCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DataFecha arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DataArchivo arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @return
     *     returns tprog.ListaDataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataUsuario consultarPerfil();

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.DataPerfil
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataPerfil verPerfil(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean perteneceUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean perteneceUsuarioMail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     */
    @WebMethod
    public void terminarControladorUsuario();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getMail();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getNick();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void setNick(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String iniciarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns tprog.ListaDataRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaDataRegistro getListaRegistro();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void agregarRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        DataRegistro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int checkNuevaVersion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "CambiarConfiguracionUsuario")
    public void cambiarConfiguracionUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1,
        @WebParam(name = "arg2", partName = "arg2")
        boolean arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void atenderReclamo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns tprog.ListaNombreJuegoConVersionesAprobadas
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListaNombreJuegoConVersionesAprobadas listarJuegosEstadista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
